### ISSUE TITLE
Support isomorphic environments

### ISSUE THREAD

**Issue by nicolasiensen** [alicelieutier/smoothScroll#15]
This seemed to be an elegant alternative to jquery's `animate` function, but I need it to be able to load in a server-side rendering environment.

Is it in your roadmap?

**Comment by alicelieutier** [comment]
You can read the discussions we've had on #11 , #12 , #13 & #14.
Where we are at now, there should be no error when loading this server side, however, the library will basically not do anything server side. This is because this library is so tightly coupled with the browser APIs, and expects things like window and document to exist in the environment it lives in.

I am not entirely sure if this is what you want, though. I have not played around with isomorphism yet, so I might be missing something.

**Comment by nicolasiensen** [comment]
Thanks @alicelieutier
