### ISSUE TITLE
Context and scrollTop

### ISSUE THREAD

**Issue by JiDai** [alicelieutier/smoothScroll#38]
Hi and thanks for this lib.
I have a pen for illustrate the problem : http://codepen.io/JiDai/pen/VKqvoZ
I can't make it work when using context. I tried different things like changing position or overflow CSS properties but nothing worked. The top values calculate is equal to 0. How can I resolve that ?

**Comment by superhussain** [comment]
Hi, I just took a look at your pen and it's working fine for me. Not sure if you changed anything since your post. If you found a solution, do you mind posting it for other people with the same issue?

**Comment by JiDai** [comment]
No I did not change anything, and I stil have the problem, the row 'SCROLL TO ME' go to the top of document (and pass behind header) and not to the top of parent.

**Comment by superhussain** [comment]
Ohh, yeah, that will always be the case. In order to solve that, you would need to offset the scroll by the height of the header. There are a few pull requests you can use that have that offset parameter. Here is one from myself: #36 and one from @cideM: #32. Both implementations would fill your needs. 😄
